<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/answer_the_query.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
database='/content/basketball.sqlite'
conn=sqlite3.connect(database)
print("Opened databbase successfully")

Opened databbase successfully

In [ ]:
import pandas as pd
tables=pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Team_Attributes,Team_Attributes,2,"CREATE TABLE `Team_Attributes` (`ID`, `ABBREVI..."
1,table,Player_Salary,Player_Salary,5,"CREATE TABLE `Player_Salary` (`slugSeason`, `n..."
2,table,Draft,Draft,36,"CREATE TABLE `Draft` (`yearDraft`, `numberPick..."
3,table,Team,Team,314,"CREATE TABLE `Team` (`id`, `full_name`, `abbre..."
4,table,Player_Attributes,Player_Attributes,315,"CREATE TABLE `Player_Attributes` (`ID`, `FIRST..."
5,table,Player,Player,617,"CREATE TABLE `Player` (`id`, `full_name`, `fir..."

In [ ]:
teams=pd.read_sql("""SELECT * FROM Team;""",conn)
teams.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [ ]:
salary=pd.read_sql("""SELECT * FROM Player_Salary;""",conn)
salary

,slugSeason,nameTeam,namePlayer,statusPlayer,isFinalSeason,isWaived,isOnRoster,isNonGuaranteed,isTeamOption,isPlayerOption,typeContractDetail,value
0,2020-21,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
1,2021-22,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
2,2022-23,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
3,2023-24,Atlanta Hawks,Bogdan Bogdanovic,current roster,1,0,1,0,0,1,Player Option,18000000.0
4,2020-21,Atlanta Hawks,Brandon Goodwin,current roster,0,0,1,0,0,0,Guaranteed,1701593.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1287,2020-21,Washington Wizards,Russell Westbrook,current roster,0,0,1,0,0,0,Guaranteed,41358814.0
1288,2021-22,Washington Wizards,Russell Westbrook,current roster,0,0,1,0,0,0,Guaranteed,44211146.0
1289,2022-23,Washington Wizards,Russell Westbrook,current roster,1,0,1,0,0,1,Player Option,47063478.0
1290,2020-21,Washington Wizards,Thomas Bryant,current roster,0,0,1,0,0,0,Guaranteed,8333333.0
1291,2021-22,Washington Wizards,Thomas Bryant,current roster,1,0,1,0,0,0,Guaranteed,8666667.0

In [ ]:
result_1=pd.read_sql("""SELECT AVG(value),MIN(value),MAX(value),
                      SUM(value)FROM Player_Salary;""",conn)
result_1

     AVG(value) MIN(value) MAX(value)    SUM(value)
0  9.762008e+06  1000000.0   999200.0  1.261251e+10

In [ ]:
result_2=pd.read_sql("""SELECT COUNT(state) FROM Team;""",conn)
result_2

   COUNT(state)
0            30

In [ ]:
result_3=pd.read_sql("""SELECT * FROM Team
                      ORDER BY year_founded;""",conn)
result_3

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
1,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
2,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
3,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
4,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
5,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
6,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
7,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
8,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
9,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
10,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
11,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
14,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
15,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
16,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
17,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
18,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
19,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
20,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
21,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
22,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
23,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
24,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988
25,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
26,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
27,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
28,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
29,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002

In [ ]:
player=pd.read_sql("""SELECT * FROM Player;""",conn)
player

           id            full_name first_name     last_name is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby         0
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz         0
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar         0
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf         0
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad         0
...       ...                  ...        ...           ...       ...
4496  1627790           Ante Zizic       Ante         Zizic         1
4497    78647             Jim Zoet        Jim          Zoet         0
4498    78648            Bill Zopf       Bill          Zopf         0
4499  1627826          Ivica Zubac      Ivica         Zubac         1
4500    78650           Matt Zunic       Matt         Zunic         0

[4501 rows x 5 columns]