<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Find_the_nulls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
database='/content/basketball.sqlite'
conn=sqlite3.connect(database)
print("Opened data successfully")

Opened data successfully

In [ ]:
import pandas as pd
tables=pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Team_Attributes,Team_Attributes,2,"CREATE TABLE `Team_Attributes` (`ID`, `ABBREVI..."
1,table,Player_Salary,Player_Salary,5,"CREATE TABLE `Player_Salary` (`slugSeason`, `n..."
2,table,Draft,Draft,36,"CREATE TABLE `Draft` (`yearDraft`, `numberPick..."
3,table,Team,Team,314,"CREATE TABLE `Team` (`id`, `full_name`, `abbre..."
4,table,Player_Attributes,Player_Attributes,315,"CREATE TABLE `Player_Attributes` (`ID`, `FIRST..."
5,table,Player,Player,617,"CREATE TABLE `Player` (`id`, `full_name`, `fir..."

In [ ]:
draft=pd.read_sql("""SELECT *
                        FROM Draft;""",conn)
draft

,yearDraft,numberPickOverall,numberRound,numberRoundPick,namePlayer,slugTeam,nameOrganizationFrom,typeOrganizationFrom,idPlayer,idTeam,nameTeam,cityTeam,teamName,PLAYER_PROFILE_FLAG,slugOrganizationTypeFrom,locationOrganizationFrom
0,2020.0,1.0,1.0,1.0,Anthony Edwards,MIN,Georgia,College/University,1630162.0,1610612750.0,Minnesota Timberwolves,Minnesota,Timberwolves,1.0,COL,
1,2020.0,2.0,1.0,2.0,James Wiseman,GSW,Memphis,College/University,1630164.0,1610612744.0,Golden State Warriors,Golden State,Warriors,1.0,COL,
2,2020.0,3.0,1.0,3.0,LaMelo Ball,CHA,Illawarra,Other Team/Club,1630163.0,1610612766.0,Charlotte Hornets,Charlotte,Hornets,1.0,PRO,Australia
3,2020.0,4.0,1.0,4.0,Patrick Williams,CHI,Florida State,College/University,1630172.0,1610612741.0,Chicago Bulls,Chicago,Bulls,1.0,COL,
4,2020.0,5.0,1.0,5.0,Isaac Okoro,CLE,Auburn,College/University,1630171.0,1610612739.0,Cleveland Cavaliers,Cleveland,Cavaliers,1.0,COL,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7885,1949.0,6.0,1.0,6.0,Ron Livingstone,BAL,Wyoming,College/University,77392.0,1610610024.0,Baltimore Bullets,Baltimore,Bullets,1.0,COL,
7886,1949.0,7.0,1.0,7.0,Dick McGuire,NYK,St. John's (NY),College/University,77537.0,1610612752.0,New York Knicks,New York,Knicks,1.0,COL,
7887,1949.0,8.0,1.0,8.0,Wallace Jones,WAS,Kentucky,College/University,77199.0,1610610036.0,Washington Capitols,Washington,Capitols,1.0,COL,
7888,1949.0,9.0,1.0,9.0,Jack Kerris,CHS,Loyola-Chicago,College/University,77249.0,1610610025.0,Chicago Stags,Chicago,Stags,1.0,COL,
7889,1949.0,10.0,1.0,10.0,Frank Saul,ROC,Seton Hall,College/University,78063.0,1610612758.0,Rochester Royals,Rochester,Royals,1.0,COL,

In [ ]:
null_Org=pd.read_sql("""SELECT *
                        FROM Draft
                        WHERE nameOrganizationFrom IS NULL;""",conn)
null_Org

Empty DataFrame
Columns: [yearDraft, numberPickOverall, numberRound, numberRoundPick, namePlayer, slugTeam, nameOrganizationFrom, typeOrganizationFrom, idPlayer, idTeam, nameTeam, cityTeam, teamName, PLAYER_PROFILE_FLAG, slugOrganizationTypeFrom, locationOrganizationFrom]
Index: []

In [ ]:
team=pd.read_sql("""SELECT *
                        FROM Team;""",conn)
team

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [ ]:
result1=pd.read_sql("""SELECT *
                        FROM Team
                        ORDER BY year_founded;""",conn)
result1.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
1,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
2,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
3,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
4,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948

In [ ]:
result1=pd.read_sql("""SELECT *
                        FROM Team
                        ORDER BY year_founded DESC;""",conn)
result1.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
1,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
2,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
3,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
4,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989