<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/JOINS_IN_SQL_jpynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

In [ ]:
database='/content/database.sqlite'
conn=sqlite3.connect(database)
tables=pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [ ]:
joined_city=pd.read_sql("""SELECT c.Country_Id,c.Country_Name,ci.City_Name
                        FROM country c
                        INNER JOIN city ci
                        ON c.Country_Id==ci.Country_Id;""",conn)
joined_city

    Country_Id  Country_Name       City_Name
0            1         India       Bangalore
1            1         India      Chandigarh
2            1         India           Delhi
3            1         India          Mumbai
4            1         India         Kolkata
5            1         India          Jaipur
6            1         India       Hyderabad
7            1         India         Chennai
8            2  South Africa       Cape Town
9            2  South Africa  Port Elizabeth
10           2  South Africa          Durban
11           2  South Africa       Centurion
12           2  South Africa     East London
13           2  South Africa    Johannesburg
14           2  South Africa       Kimberley
15           2  South Africa    Bloemfontein
16           1         India       Ahmedabad
17           1         India         Cuttack
18           1         India          Nagpur
19           1         India      Dharamsala
20           1         India           Kochi
21           1         India          Indore
22           1         India   Visakhapatnam
23           1         India            Pune
24           1         India          Raipur
25           1         India          Ranchi
26           3         U.A.E       Abu Dhabi
27           1         India          Rajkot
28           1         India          Kanpur

In [ ]:
joined_left=pd.read_sql("""SELECT *
                        FROM player
                        LEFT JOIN season
                        ON player.Player_Id==season.Man_of_the_Series""",conn)
joined_left

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name,Season_Id,Man_of_the_Series,Orange_Cap,Purple_Cap,Season_Year
0,1,SC Ganguly,1972-07-08 00:00:00,1,1.0,1,NaN,NaN,NaN,NaN,NaN
1,2,BB McCullum,1981-09-27 00:00:00,2,1.0,4,NaN,NaN,NaN,NaN,NaN
2,3,RT Ponting,1974-12-19 00:00:00,2,1.0,5,NaN,NaN,NaN,NaN,NaN
3,4,DJ Hussey,1977-07-15 00:00:00,2,2.0,5,NaN,NaN,NaN,NaN,NaN
4,5,Mohammad Hafeez,1980-10-17 00:00:00,2,2.0,6,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
465,465,DL Chahar,1992-08-07 00:00:00,2,1.0,1,NaN,NaN,NaN,NaN,NaN
466,466,P Dharmani,1974-09-27 00:00:00,2,NaN,1,NaN,NaN,NaN,NaN,NaN
467,467,RV Pawar,1979-09-06 00:00:00,1,7.0,1,NaN,NaN,NaN,NaN,NaN
468,468,KH Devdhar,1989-12-14 00:00:00,2,NaN,1,NaN,NaN,NaN,NaN,NaN
469,469,T Mishra,1986-12-22 00:00:00,2,3.0,1,NaN,NaN,NaN,NaN,NaN

In [ ]:
joined_cross=pd.read_sql("""SELECT c.Country_Id,c.Country_Name,ci.City_Name
                        FROM country c
                        CROSS JOIN city ci""",conn)
joined_cross

     Country_Id Country_Name   City_Name
0             1        India   Bangalore
1             1        India  Chandigarh
2             1        India       Delhi
3             1        India      Mumbai
4             1        India     Kolkata
..          ...          ...         ...
343          12  Netherlands      Raipur
344          12  Netherlands      Ranchi
345          12  Netherlands   Abu Dhabi
346          12  Netherlands      Rajkot
347          12  Netherlands      Kanpur

[348 rows x 3 columns]

In [ ]:
union=pd.read_sql("""SELECT Player_Name
                        FROM player
                        UNION
                        SELECT Team_Name
                        FROM team""",conn)
union

        Player_Name
0    A Ashish Reddy
1        A Chandila
2          A Chopra
3        A Flintoff
4          A Kumble
..              ...
477     Younis Khan
478       YS Chahal
479    Yuvraj Singh
480     YV Takawale
481          Z Khan

[482 rows x 1 columns]