<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Let's_join_the_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

In [ ]:
database='/content/basketball.sqlite'
conn=sqlite3.connect(database)
print('Opened data successfully')

Opened data successfully

In [ ]:
tables=pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Team_Attributes,Team_Attributes,2,"CREATE TABLE `Team_Attributes` (`ID`, `ABBREVI..."
1,table,Player_Salary,Player_Salary,5,"CREATE TABLE `Player_Salary` (`slugSeason`, `n..."
2,table,Draft,Draft,36,"CREATE TABLE `Draft` (`yearDraft`, `numberPick..."
3,table,Team,Team,314,"CREATE TABLE `Team` (`id`, `full_name`, `abbre..."
4,table,Player_Attributes,Player_Attributes,315,"CREATE TABLE `Player_Attributes` (`ID`, `FIRST..."
5,table,Player,Player,617,"CREATE TABLE `Player` (`id`, `full_name`, `fir..."

In [ ]:
player=pd.read_sql("""SELECT *
                        FROM Player;""",conn)
player

           id            full_name first_name     last_name is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby         0
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz         0
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar         0
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf         0
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad         0
...       ...                  ...        ...           ...       ...
4496  1627790           Ante Zizic       Ante         Zizic         1
4497    78647             Jim Zoet        Jim          Zoet         0
4498    78648            Bill Zopf       Bill          Zopf         0
4499  1627826          Ivica Zubac      Ivica         Zubac         1
4500    78650           Matt Zunic       Matt         Zunic         0

[4501 rows x 5 columns]

In [ ]:
salary=pd.read_sql("""SELECT *
                        FROM Player_Salary;""",conn)
salary

,slugSeason,nameTeam,namePlayer,statusPlayer,isFinalSeason,isWaived,isOnRoster,isNonGuaranteed,isTeamOption,isPlayerOption,typeContractDetail,value
0,2020-21,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
1,2021-22,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
2,2022-23,Atlanta Hawks,Bogdan Bogdanovic,current roster,0,0,1,0,0,0,Guaranteed,18000000.0
3,2023-24,Atlanta Hawks,Bogdan Bogdanovic,current roster,1,0,1,0,0,1,Player Option,18000000.0
4,2020-21,Atlanta Hawks,Brandon Goodwin,current roster,0,0,1,0,0,0,Guaranteed,1701593.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1287,2020-21,Washington Wizards,Russell Westbrook,current roster,0,0,1,0,0,0,Guaranteed,41358814.0
1288,2021-22,Washington Wizards,Russell Westbrook,current roster,0,0,1,0,0,0,Guaranteed,44211146.0
1289,2022-23,Washington Wizards,Russell Westbrook,current roster,1,0,1,0,0,1,Player Option,47063478.0
1290,2020-21,Washington Wizards,Thomas Bryant,current roster,0,0,1,0,0,0,Guaranteed,8333333.0
1291,2021-22,Washington Wizards,Thomas Bryant,current roster,1,0,1,0,0,0,Guaranteed,8666667.0

In [ ]:
join=pd.read_sql("""SELECT DISTINCT ps.nameTeam, ps.namePlayer, ps.value, p.is_active
                    FROM Player p
                    JOIN Player_Salary ps
                    ON p.full_name = ps.namePlayer;""",conn)
join

                 nameTeam    namePlayer       value is_active
0    New Orleans Pelicans  Steven Adams  17073171.0         1
1    New Orleans Pelicans  Steven Adams  17926829.0         1
2    New Orleans Pelicans  Steven Adams  29592695.0         1
3              Miami Heat   Bam Adebayo  28103500.0         1
4              Miami Heat   Bam Adebayo  30351780.0         1
..                    ...           ...         ...       ...
893         Atlanta Hawks    Trae Young   6571800.0         1
894         Atlanta Hawks    Trae Young   8326471.0         1
895     Charlotte Hornets   Cody Zeller  15415730.0         1
896  Los Angeles Clippers   Ivica Zubac   7000000.0         1
897  Los Angeles Clippers   Ivica Zubac   7518518.0         1

[898 rows x 4 columns]