<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/SQL_CONSTRAINTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ACTIVITY 1

In [ ]:
import sqlite3
database='CLASS.sqlite'
conn=sqlite3.connect(database)
print("Opened database successfully")

Opened database successfully

In [ ]:
conn.execute("""CREATE TABLE CLASS_10
              (SNO INT PRIMARY KEY NOT NULL,
              Roll_No INT NOT NULL,
              NAME TEXT NOT NULL,
              AGE INT DEFAULT(15),
              GENDER TEXT NOT NULL,
              Email_ID TEXT NOT NULL,
              Contact_No REAL NOT NULL);""")
print("Table created successfully")

Table created successfully

In [ ]:
conn.execute("INSERT INTO CLASS_10(SNO,Roll_No,NAME,AGE,GENDER,Email_ID,Contact_No)\
              VALUES(1,1,'ALLEN',14,'MALE','allen@gmail.com',8080900)");
conn.execute("INSERT INTO CLASS_10(SNO,Roll_No,NAME,AGE,GENDER,Email_ID,Contact_No)\
              VALUES(2,2,'BOB',15,'MALE','bob@gmail.com',8080901)");
conn.execute("INSERT INTO CLASS_10(SNO,Roll_No,NAME,AGE,GENDER,Email_ID,Contact_No)\
              VALUES(3,3,'ALISHA',14,'FEMALE','alish@gmail.com',9080900)");
conn.execute("INSERT INTO CLASS_10(SNO,Roll_No,NAME,AGE,GENDER,Email_ID,Contact_No)\
              VALUES(4,4,'JEFF',15,'MALE','jeff@gmail.com',9900900)");
conn.commit()
print("Records created successfully")

Records created successfully

In [ ]:
import pandas as pd
tables=pd.read_sql("""SELECT *
                    FROM sqlite_master
                    WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,CLASS_10,CLASS_10,2,CREATE TABLE CLASS_10\n (SNO INT ...

In [ ]:
class_10=pd.read_sql("""SELECT * FROM CLASS_10;""",conn)
class_10.head()

   SNO  Roll_No    NAME  AGE  GENDER         Email_ID  Contact_No
0    1        1   ALLEN   14    MALE  allen@gmail.com   8080900.0
1    2        2     BOB   15    MALE    bob@gmail.com   8080901.0
2    3        3  ALISHA   14  FEMALE  alish@gmail.com   9080900.0
3    4        4    JEFF   15    MALE   jeff@gmail.com   9900900.0

# ACTIVITY 2

In [ ]:
import pandas as pd
import numpy as np
import sqlite3
database='/content/database.sqlite'
connect=sqlite3.connect(database)
print("Opened data successfully")
df=pd.read_sql("""SELECT * FROM sqlite_master
                WHERE type='table';""",connect)
df

Opened data successfully

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [ ]:
player_match=pd.read_sql("""SELECT * FROM Player_Match;""",connect)
player_match.head()

   Match_Id  Player_Id  Role_Id  Team_Id
0    335987          1        1        1
1    335987          2        3        1
2    335987          3        3        1
3    335987          4        3        1
4    335987          5        3        1

In [ ]:
null_player_match=pd.read_sql("""SELECT *
                                FROM Player_Match
                                WHERE Team_Id IS NULL;""",connect)
null_player_match

Empty DataFrame
Columns: [Match_Id, Player_Id, Role_Id, Team_Id]
Index: []

In [ ]:
toss_dec=pd.read_sql("""SELECT *
                       FROM Match;""",connect)
toss_dec.head()

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0

In [ ]:
null_match=pd.read_sql("""SELECT *
                         FROM Match
                         WHERE MATCH_Winner IS NULL;""",connect)
null_match

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,501270,6,10,2011-05-21 00:00:00,4,3,6,2,3,None,2,None,None
1,829768,2,5,2015-04-29 00:00:00,8,1,5,1,3,None,2,None,None
2,829818,2,6,2015-05-17 00:00:00,8,1,2,1,3,None,2,None,None