<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Statistics_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded= files.upload()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
#import dataset
data=pd.read_csv('Titanic Dataset.csv')
data.head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Gender
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,female
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,female
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,male

In [ ]:
#check the datatype
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Gender          object
dtype: object

In [ ]:
#check null values
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          156
Embarked         0
Gender           0
dtype: int64

In [ ]:
#activity 2
#mean value of age and fare
mean_age=np.mean(data['Age'])
print('Mean Age of Passengers is-',mean_age)
mean_fare=np.mean(data['Fare'])
print('Mean Fare is-',mean_fare)

Mean Age of Passengers is- 27.76173076923077
Mean Fare is- 27.28388717948718

In [ ]:
#median value of age and fare
median_age=np.median(data['Age'])
print('Median value of Age-',median_age)
median_fare=np.median(data['Fare'])
print('Median value of Fare-',median_fare)

Median value of Age- 27.76173076923077
Median value of Fare- 15.05

In [ ]:
import statistics as stats
#mode value of age and PClass
mode_age=stats.mode(data['Age'])
print("Mode value of Age-",mode_age)
mode_class=stats.mode(data['Pclass'])
print("Mode value of PClass-",mode_class)

Mode value of Age- 27.76173076923077
Mode value of PClass- 3

In [ ]:
#mode value of categorical data(gender)
mode_gender=data['Gender'].value_counts().index[0]
print("Mode of feature gender-",mode_gender)

Mode of feature gender- male